apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  selector:
    app: vllm-tpu
  type: LoadBalancer    
  ports:
    - name: http
      protocol: TCP
      port: 8000  
      targetPort: 8000
